export const users = [
  {
    id: 1,
    image: "post/a.jpg",
    name: "cris pack",
  },
  {
    id: 2,
    image: "post/b.jpg",
    name: "candy",
  },
  {
    id: 3,
    image: "post/c.jpg",
    name: "andy",
  },
  {
    id: 4,
    image: "post/d.jpg",
    name: "Craken",
  },
  {
    id: 4,
    image: "post/e.jpg",
    name: "Bosso",
  },
  {
    id: 5,
    image: "post/f.jpg",
    name: "Daby",
  },
  {
    id: 6,
    image: "post/g.jpg",
    name: "Silver",
  },
  {
    id: 7,
    image: "post/h.jpg",
    name: "moscow",
  },
  {
    id: 8,
    image: "post/i.jpg",
    name: "pazo",
  },
  {
    id: 9,
    image: "post/j.jpg",
    name: "Chary",
  },
  {
    id: 10,
    image: "post/k.jpg",
    name: "Adolph",
  },
  {
    id: 11,
    image: "post/l.jpg",
    name: "tony",
  },
];
export const Posts = [
  {
    id: 1,
    desc: "no haters just inspires",
    photo: "profile/c1.jpg",
    date: "5 min ago",
    userId: 1,
    like: 32,
    dislike: 1,
    comment: 9,
  },
  {
    id: 2,
    desc: "We fly to high",
    photo: "profile/c2.jpg",
    date: "10 min ago",
    userId: 2,
    like: 2,
    dislike: 1,
    comment: 12,
  },
  {
    id: 3,
    desc: "we sad",
    photo: "profile/c3.jpg",
    date: "5 days ago",
    userId: 3,
    like: 123,
    dislike: 1,
    comment: 39,
  },
  {
    id: 4,
    desc: "No love",
    photo: "profile/c4.jpg",
    date: "10 hours ago",
    userId: 4,
    like: 32,
    dislike: 1,
    comment: 19,
  },
  {
    id: 5,
    desc: "twbigezeho",
    photo: "profile/c5.jpg",
    date: "4 hours",
    userId: 5,
    like: 32,
    dislike: 1,
    comment: 9,
  },
  {
    id: 6,
    desc: "no ghd hjdgc jh",
    photo: "profile/c6.jpg",
    date: "5 min ago",
    userId: 6,
    like: 3,
    dislike: 1,
    comment: 0,
  },
  {
    id: 7,
    desc: "no hatefh htrwt",
    photo: "profile/c7.jpg",
    date: "50 min ago",
    userId: 7,
    like: 2,
    dislike: 1,
    comment: 0,
  },
  {
    id: 8,
    desc: "no hahgjf fgsr4",
    photo: "profile/c8.jpg",
    date: "just now",
    userId: 8,
    like: 1,
    dislike: 1,
    comment: 0,
  },
  {
    id: 9,
    desc: "no haters guj teyu65 ",
    photo: "profile/c9.jpg",
    date: "3 months ago",
    userId: 9,
    like: 453,
    dislike: 1,
    comment: 119,
  },
  {
    id: 10,
    desc: "no gth65 gh56yy sft45",
    photo: "profile/c10.jpg",
    date: "5 months ago",
    userId: 10,
    like: 3,
    dislike: 1,
    comment: 0,
  },
  {
    id: 11,
    desc: "no mercy",
    photo: "profile/c11.jpg",
    date: "5 min ago",
    userId: 11,
    like: 32,
    dislike: 1,
    comment: 9,
  },
];
